name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and Run Tests
      run: |
        yarn install
        yarn build
        yarn test
